# Generated by Django 3.1.4 on 2021-01-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210106_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('email', 'phone_number', 'name')},
        ),
    ]
