# Generated by Django 3.1.4 on 2021-01-06 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_store'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default='5b881a64-ac3f-43c4-b528-a634f0fe85ab', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='users.company'),
        ),
    ]
