# Generated by Django 3.1.4 on 2021-02-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210106_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='issues',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.Issue'),
        ),
    ]
